
// Define the structure of the startup blueprint generated by Gemini
export interface Blueprint {
  id: string;
  originalIdea: string;
  title: string;
  createdAt: number;
  content: {
    blueprint: {
      problemStatement: string;
      targetUsers: string;
      coreFeatures: string;
      userFlow: string;
      systemArchitecture: string;
      databaseSchema: string;
      apiDesign: string;
      geminiIntegration: string;
      techStack: string;
      securityPrivacy: string;
      timeline: string;
      futureScaling?: string;
    };
    roadmap: {
      milestones: Array<{ name: string; start: number; end: number; description: string }>;
      resourceAllocation: Array<{ name: string; value: number; description: string }>;
      priorityQuadrants: {
        quickWins: Array<{ name: string; reason: string }>;
        strategicBets: Array<{ name: string; reason: string }>;
        maintenance: Array<{ name: string; reason: string }>;
        distractions: Array<{ name: string; reason: string }>;
      };
    };
    competitors: {
      analysis: string;
      list: Array<{ 
        name: string; 
        strength: string; 
        weakness: string; 
        marketPosition: string; 
        price: string; 
        differentiator: string; 
      }>;
      comparisonMetrics: Array<{ metric: string; ourProduct: string; competitorA: string; competitorB: string }>;
      differentiators: string;
    };
    caseStudies: Array<{
      name: string;
      founders: string;
      revenue: string;
      logoUrl: string;
      problem: string;
      approach: string;
      outcome: string;
    }>;
  };
}

export type TabType = 'blueprint' | 'roadmap' | 'competitors' | 'caseStudies';

export interface HistoryItem {
  id: string;
  title: string;
  idea: string;
  timestamp: number;
}
